#!/usr/bin/env python3
# This script reads through all archived emails and attempts to parse them as a
# patch, adding or removing their patch classification accordingly.
import sys
from listssrht.app import db
from listssrht.types import Email

nemails = Email.query.count()
for i, email in enumerate(Email.query.all()):
    sys.stdout.write(f"\r{i+1}/{nemails}")
    email.patch()

print("\nCommitting...")
db.session.commit()
print("Done.")
