#!/bin/sh -eu
arch="${1:-amd64}"
export netbsd_dist="https://cdn.netbsd.org/pub/NetBSD/NetBSD-10.0/$arch"
export netbsd_suffix="tar.xz"
export pkgin_dist="cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/$arch/10.0/All"
exec ../genimg "$@"
