[options]
HoldPkg     = pacman glibc
Architecture = auto
IgnorePkg   = linux linux-firmware
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = https://geo.mirror.pkgbuild.com/core/os/$arch
[extra]
Server = https://geo.mirror.pkgbuild.com/extra/os/$arch
[multilib]
Server = https://geo.mirror.pkgbuild.com/multilib/os/$arch
